<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OCA"
    nsURI="http://swt.informatik.uni-mannheim.de/OCA" nsPrefix="OCA">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="ecore:EClass ../../uni-mannheim.informatik.swt.models.plm/model/PLM.ecore#//PElement"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
