<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PLM"
    nsURI="http://swt.informatik.uni-mannheim.de/PLM" nsPrefix="PLM">
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ontology">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ontologicLevels" upperBound="-1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OwnedElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalElement" eSuperTypes="#//OwnedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//OwnedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ontology" lowerBound="1"
        eType="#//Ontology" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PotentElement" eSuperTypes="#//OwnedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="potency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetRelationship" eSuperTypes="#//LogicalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//LogicalElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instantiation" eSuperTypes="#//LogicalElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indirect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Clabject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Complement" eSuperTypes="#//SetRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equals" eSuperTypes="#//SetRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inversion" eSuperTypes="#//SetRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryGeneralization" eSuperTypes="#//Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtype" eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" eType="#//Clabject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleGeneralization" eSuperTypes="#//Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtype" eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" lowerBound="1"
        upperBound="-1" eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intersection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="union" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleSpecialization" eSuperTypes="#//Generalization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtype" lowerBound="1"
        upperBound="-1" eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="complete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disjoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clabject" eSuperTypes="#//PotentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" upperBound="-1"
        eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" lowerBound="1"
        upperBound="-1" eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//PotentElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainEntity" eSuperTypes="#//Clabject"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainConnection" eSuperTypes="#//Clabject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participant" lowerBound="2"
        upperBound="-1" eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleName" lowerBound="2"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" lowerBound="2" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" lowerBound="2" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigable" lowerBound="2"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="#//Clabject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Clabject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" upperBound="-1"
        eType="#//PotentElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        upperBound="-1" eType="#//PotentElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OntologicLevel" eSuperTypes="#//OwnedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//OwnedElement" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
