(* FACTOR TEST FILE FROM ISO *)
aa = "A";
bb = 3 * aa, "B";
cc = 3 * [aa], "C";
dd = {aa}, "D";
ee = aa, {aa}, "E";
ff = 3 * aa, 3 * [aa], "F"; 
gg = 3 * {aa}, "D";
hh = 3 * "H", "D";
ii = 3 * ["I"], "D";