<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ebnfmm" nsURI="http://swt.informatik.uni-mannheim.de/ebnfmm"
    nsPrefix="ebnfmm">
  <eClassifiers xsi:type="ecore:EClass" name="EBNFDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//EBNFDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" ordered="false"
        upperBound="-1" eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//NonTerminal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//NonTerminal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" upperBound="-1"
        eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonTerminal" eSuperTypes="#//Symbol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Terminal" eSuperTypes="#//Symbol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Control" eSuperTypes="#//Symbol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="Option" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repetition" eSuperTypes="#//Control"/>
</ecore:EPackage>
