<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ebnfmm" nsURI="http://swt.informatik.uni-mannheim.de/ebnfmm"
    nsPrefix="ebnfmm">
  <eClassifiers xsi:type="ecore:EClass" name="EBNFDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" ordered="false"
        upperBound="-1" eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaIdentifier" lowerBound="1"
        eType="#//NonTerminal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitionList" lowerBound="1"
        upperBound="-1" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonTerminal" eSuperTypes="#//ReferenceableSymbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Terminal" eSuperTypes="#//NonReferenceableSymbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminalString" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" abstract="true" eSuperTypes="#//NonReferenceableSymbol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" upperBound="-1"
        eType="#//Dummy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="Option" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repetition" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceableSymbol" abstract="true"
      eSuperTypes="#//Symbol"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonReferenceableSymbol" abstract="true"
      eSuperTypes="#//Symbol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dummy">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="validDummy"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//ReferenceableSymbol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containment" eType="#//NonReferenceableSymbol"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//Control"/>
</ecore:EPackage>
